package net.deuce.clmanager.domain;
// Generated Apr 11, 2008 1:02:39 PM by Hibernate Tools 3.2.0.CR1



/**
 * Category generated by hbm2java
 */
public class CategorySubscription  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private UserPreferences userPreferences;
    private boolean subscribed;
    private boolean filtered;
    private Category category;
    
    public CategorySubscription() {
    }

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public boolean isSubscribed() {
        return subscribed;
    }

    public void setSubscribed(boolean subscribed) {
        this.subscribed = subscribed;
    }

    public boolean isFiltered() {
        return filtered;
    }

    public void setFiltered(boolean filtered) {
        this.filtered = filtered;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }
    
    public UserPreferences getUserPreferences() {
        return userPreferences;
    }

    public void setUserPreferences(UserPreferences userPreferences) {
        this.userPreferences = userPreferences;
    }

    @Override
    public boolean equals(Object obj) {
        boolean b = false;
        if (obj != null && obj instanceof CategorySubscription) {
            CategorySubscription that = (CategorySubscription)obj;
            UserPreferences thatUp = that.getUserPreferences();
            Category thatCat = that.getCategory();
            b = userPreferences.equals(thatUp) && category.equals(thatCat);
        }
        return b;
    }

    @Override
    public int hashCode() {
        return userPreferences.hashCode()+category.hashCode();
    }
}


