package net.deuce.clmanager.domain;
// Generated Apr 11, 2008 1:02:39 PM by Hibernate Tools 3.2.0.CR1



/**
 * Post generated by hbm2java
 */
public class PostActivities  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private String username;
    private boolean responded;
    private boolean viewed;
    private boolean favorite;
    private Post post;

    public PostActivities() {
    }
    
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public boolean isResponded() {
        return this.responded;
    }
    
    public void setResponded(boolean responded) {
        this.responded = responded;
    }
    
    public boolean isViewed() {
        return this.viewed;
    }
    
    public void setViewed(boolean viewed) {
        this.viewed = viewed;
    }

    public boolean isFavorite() {
        return favorite;
    }

    public void setFavorite(boolean favorite) {
        this.favorite = favorite;
    }

    public Post getPost() {
        return post;
    }

    public void setPost(Post post) {
        this.post = post;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    
    @Override
    public boolean equals(Object obj) {
        boolean b = false;
        if (obj != null && obj instanceof PostActivities) {
            PostActivities that = (PostActivities)obj;
            b = post.equals(that.getPost()) && username.equals(that.getUsername());
        }
        return b;
    }

    @Override
    public int hashCode() {
        return post.hashCode()+username.hashCode();
    }
}


