package net.deuce.clmanager.domain;
// Generated Apr 11, 2008 1:02:39 PM by Hibernate Tools 3.2.0.CR1



/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private String name;
    private String externalName;

    public Category() {
    }

    public Category(String name, String externalName) {
       this.name = name;
       this.externalName = externalName;
    }
    
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getExternalName() {
        return this.externalName;
    }
    
    public void setExternalName(String externalName) {
        this.externalName = externalName;
    }

    @Override
    public boolean equals(Object obj) {
        boolean b = false;
        if (obj != null && obj instanceof Category) {
            Category that = (Category)obj;
            b = name.equals(that.getName());
        }
        return b;
    }

    @Override
    public int hashCode() {
        return name.hashCode();
    }
    
}


