package net.deuce.clmanager.domain;
// Generated Apr 11, 2008 1:02:39 PM by Hibernate Tools 3.2.0.CR1



/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

    private Long id;
    private String name;
    private String url;
    
    public City() {
    }

    public City(String name, String url) {
       this.name = name;
       this.url = url;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public boolean equals(Object obj) {
        boolean b = false;
        if (obj != null && obj instanceof City) {
            b = name.equals(((City)obj).getName());
        }
        return b;
    }

    @Override
    public int hashCode() {
        return name.hashCode();
    }
    
}


