package net.deuce.clmanager.domain;

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String url;
    private String path;
    private Post post;

    public Image() {
    }

    public Image(String url, String path, Post post) {
        this.url = url;
        this.path = path;
        this.post = post;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Post getPost() {
        return post;
    }

    public void setPost(Post post) {
        this.post = post;
    }

    @Override
    public boolean equals(Object obj) {
        boolean b = false;
        if (obj != null && obj instanceof Image) {
            b = path.equals(((Image) obj).getPath());
        }
        return b;
    }

    @Override
    public int hashCode() {
        return path.hashCode();
    }

}
