package net.deuce.clmanager.domain;

/**
 * MessagePhoto generated by hbm2java
 */
public class MessagePhotoAssociation implements java.io.Serializable {

    private Long id;

    private MessageTemplate messageTemplate;

    private MessagePhoto messagePhoto;

    public MessagePhotoAssociation() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public MessageTemplate getMessageTemplate() {
        return messageTemplate;
    }

    public void setMessageTemplate(MessageTemplate messageTemplate) {
        this.messageTemplate = messageTemplate;
    }

    public MessagePhoto getMessagePhoto() {
        return messagePhoto;
    }

    public void setMessagePhoto(MessagePhoto messagePhoto) {
        this.messagePhoto = messagePhoto;
    }

    @Override
    public boolean equals(Object obj) {
        boolean b = false;
        if (obj != null && obj instanceof MessagePhotoAssociation) {
            MessagePhotoAssociation that = (MessagePhotoAssociation)obj;
            b = messageTemplate.equals(that.getMessageTemplate()) &&
                messagePhoto.equals(that.getMessagePhoto());
        }
        return b;
    }

    @Override
    public int hashCode() {
        return messageTemplate.hashCode()+messagePhoto.hashCode();
    }
}