package net.deuce.clmanager.domain;




/**
 * MessagePhoto generated by hbm2java
 */
public class MessagePhoto  implements java.io.Serializable {


     private Long id;
     private String path;

    public MessagePhoto() {
    }

    public MessagePhoto(String path) {
       this.path = path;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    @Override
    public boolean equals(Object obj) {
        boolean b = false;
        if (obj != null && obj instanceof MessagePhoto) {
            b = path.equals(((MessagePhoto)obj).getPath());
        }
        return b;
    }

    @Override
    public int hashCode() {
        return path.hashCode();
    }
}


