package net.deuce.clmanager.domain;
// Generated Apr 11, 2008 1:02:39 PM by Hibernate Tools 3.2.0.CR1



/**
 * Post generated by hbm2java
 */
public class Preference  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private UserPreferences userPreferences;
    private String name;
    private String value;

    public Preference() {
    }
    
    public Preference(String name, String value) {
        this.name = name;
        this.value = value;
    }
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public UserPreferences getUserPreferences() {
        return userPreferences;
    }

    public void setUserPreferences(UserPreferences userPreferences) {
        this.userPreferences = userPreferences;
    }

    @Override
    public String toString() {
        return "{" + name + ": " + value + "}";
    }

    @Override
    public boolean equals(Object obj) {
        boolean b = false;
        if (obj instanceof Preference) {
            Preference that = (Preference)obj;
            b = userPreferences.equals(that.getUserPreferences()) &&
                name.equals(that.getName());
        }
        return b;
    }

    @Override
    public int hashCode() {
        return name.hashCode()+userPreferences.hashCode();
    }

}


