insert into message_photo values(1, '/images/messagePhotos/IMG_0048.jpg');
insert into message_photo values(2, '/images/messagePhotos/P0000855.jpg');
insert into message_photo values(3, '/images/messagePhotos/P0000883.jpg');
insert into message_photo values(4, '/images/messagePhotos/P0000887.jpg');
insert into category (category_id, name, external_name) values (1, 'community - artists', 'ats');
insert into category (category_id, name, external_name) values (2, 'community - classes', 'cal/#classes');
insert into category (category_id, name, external_name) values (3, 'community - events', 'cal');
insert into category (category_id, name, external_name) values (4, 'community - general', 'com');
insert into category (category_id, name, external_name) values (5, 'community - groups', 'grp');
insert into category (category_id, name, external_name) values (6, 'community - pets', 'pet');
insert into category (category_id, name, external_name) values (7, 'community - politics', 'pol');
insert into category (category_id, name, external_name) values (8, 'community - childcare', 'kid');
insert into category (category_id, name, external_name) values (9, 'community - local news', 'vnn');
insert into category (category_id, name, external_name) values (10, 'community - lost+found', 'laf');
insert into category (category_id, name, external_name) values (11, 'community - musicians', 'muc');
insert into category (category_id, name, external_name) values (12, 'community - rideshare', 'rid');
insert into category (category_id, name, external_name) values (13, 'community - volunteers', 'vol');
insert into category (category_id, name, external_name) values (14, 'personals - strictly platonic', 'stp');
insert into category (category_id, name, external_name) values (15, 'personals - women seek women', 'w4w');
insert into category (category_id, name, external_name) values (16, 'personals - women seeking men', 'w4m');
insert into category (category_id, name, external_name) values (17, 'personals - men seeking women', 'm4w');
insert into category (category_id, name, external_name) values (18, 'personals - men seeking men', 'm4m');
insert into category (category_id, name, external_name) values (19, 'personals - misc romance', 'msr');
insert into category (category_id, name, external_name) values (20, 'personals - casual encounters', 'cas');
insert into category (category_id, name, external_name) values (21, 'personals - missed connections', 'mis');
insert into category (category_id, name, external_name) values (22, 'personals - rants and raves', 'rnr');
insert into category (category_id, name, external_name) values (23, 'housing - apts / housing', 'apa');
insert into category (category_id, name, external_name) values (24, 'housing - housing swap', 'swp');
insert into category (category_id, name, external_name) values (25, 'housing - housing wanted', 'hsw');
insert into category (category_id, name, external_name) values (26, 'housing - office / commercial', 'off');
insert into category (category_id, name, external_name) values (27, 'housing - parking / storage', 'prk');
insert into category (category_id, name, external_name) values (28, 'housing - real estate for sale', 'rfs');
insert into category (category_id, name, external_name) values (29, 'housing - rooms / shared', 'roo');
insert into category (category_id, name, external_name) values (30, 'housing - sublets / temporary', 'sub');
insert into category (category_id, name, external_name) values (31, 'housing - vacation rentals', 'vac');
insert into category (category_id, name, external_name) values (32, 'for sale - barter', 'bar');
insert into category (category_id, name, external_name) values (33, 'for sale - bikes', 'bik');
insert into category (category_id, name, external_name) values (34, 'for sale - boats', 'boa');
insert into category (category_id, name, external_name) values (35, 'for sale - books', 'bks');
insert into category (category_id, name, external_name) values (36, 'for sale - business', 'bfs');
insert into category (category_id, name, external_name) values (37, 'for sale - computer', 'sys');
insert into category (category_id, name, external_name) values (38, 'for sale - free', 'zip');
insert into category (category_id, name, external_name) values (39, 'for sale - general', 'for');
insert into category (category_id, name, external_name) values (40, 'for sale - jewelry', 'jwl');
insert into category (category_id, name, external_name) values (41, 'for sale - material', 'mat');
insert into category (category_id, name, external_name) values (42, 'for sale - rvs', 'rvs');
insert into category (category_id, name, external_name) values (43, 'for sale - sporting', 'spo');
insert into category (category_id, name, external_name) values (44, 'for sale - tickets', 'tix');
insert into category (category_id, name, external_name) values (45, 'for sale - tools', 'tls');
insert into category (category_id, name, external_name) values (46, 'for sale - wanted', 'wan');
insert into category (category_id, name, external_name) values (47, 'for sale - arts+crafts', 'art');
insert into category (category_id, name, external_name) values (48, 'for sale - auto parts', 'pts');
insert into category (category_id, name, external_name) values (49, 'for sale - baby+kids', 'bab');
insert into category (category_id, name, external_name) values (50, 'for sale - cars+trucks', 'car');
insert into category (category_id, name, external_name) values (51, 'for sale - cds/dvd/vhs', 'emd');
insert into category (category_id, name, external_name) values (52, 'for sale - clothes+acc', 'clo');
insert into category (category_id, name, external_name) values (53, 'for sale - collectibles', 'clt');
insert into category (category_id, name, external_name) values (54, 'for sale - electronics', 'ele');
insert into category (category_id, name, external_name) values (55, 'for sale - farm+garden', 'grd');
insert into category (category_id, name, external_name) values (56, 'for sale - furniture', 'fur');
insert into category (category_id, name, external_name) values (57, 'for sale - games+toys', 'tag');
insert into category (category_id, name, external_name) values (58, 'for sale - garage sale', 'gms');
insert into category (category_id, name, external_name) values (59, 'for sale - household', 'hsh');
insert into category (category_id, name, external_name) values (60, 'for sale - motorcycles', 'mcy');
insert into category (category_id, name, external_name) values (61, 'for sale - music instr', 'msg');
insert into category (category_id, name, external_name) values (62, 'for sale - photo+video', 'pho');
insert into category (category_id, name, external_name) values (63, 'services - beauty', 'bts');
insert into category (category_id, name, external_name) values (64, 'services - computer', 'cps');
insert into category (category_id, name, external_name) values (65, 'services - creative', 'crs');
insert into category (category_id, name, external_name) values (66, 'services - erotic', 'ers');
insert into category (category_id, name, external_name) values (67, 'services - event', 'evs');
insert into category (category_id, name, external_name) values (68, 'services - legal', 'lgs');
insert into category (category_id, name, external_name) values (69, 'services - lessons', 'lss');
insert into category (category_id, name, external_name) values (70, 'services - automotive', 'aos');
insert into category (category_id, name, external_name) values (71, 'services - financial', 'fns');
insert into category (category_id, name, external_name) values (72, 'services - household', 'hss');
insert into category (category_id, name, external_name) values (73, 'services - labor/move', 'lbs');
insert into category (category_id, name, external_name) values (74, 'services - real estate', 'rts');
insert into category (category_id, name, external_name) values (75, 'services - skill''d trade', 'sks');
insert into category (category_id, name, external_name) values (76, 'services - sm biz ads', 'biz');
insert into category (category_id, name, external_name) values (77, 'services - therapeutic', 'ths');
insert into category (category_id, name, external_name) values (78, 'services - travel/vac', 'trv');
insert into category (category_id, name, external_name) values (79, 'services - write/ed/tr8', 'wet');
insert into category (category_id, name, external_name) values (80, 'jobs - accounting+finance', 'acc');
insert into category (category_id, name, external_name) values (81, 'jobs - admin / office', 'ofc');
insert into category (category_id, name, external_name) values (82, 'jobs - arch / engineering', 'egr');
insert into category (category_id, name, external_name) values (83, 'jobs - art / media / design', 'med');
insert into category (category_id, name, external_name) values (84, 'jobs - biotech / science', 'sci');
insert into category (category_id, name, external_name) values (85, 'jobs - business / mgmt', 'bus');
insert into category (category_id, name, external_name) values (86, 'jobs - customer service', 'csr');
insert into category (category_id, name, external_name) values (87, 'jobs - education', 'edu');
insert into category (category_id, name, external_name) values (88, 'jobs - food / bev / hosp', 'fbh');
insert into category (category_id, name, external_name) values (89, 'jobs - general labor', 'lab');
insert into category (category_id, name, external_name) values (90, 'jobs - government', 'gov');
insert into category (category_id, name, external_name) values (91, 'jobs - human resources', 'hum');
insert into category (category_id, name, external_name) values (92, 'jobs - internet engineers', 'eng');
insert into category (category_id, name, external_name) values (93, 'jobs - legal  /  paralegal', 'lgl');
insert into category (category_id, name, external_name) values (94, 'jobs - manufacturing', 'mnu');
insert into category (category_id, name, external_name) values (95, 'jobs - marketing / pr / ad', 'mar');
insert into category (category_id, name, external_name) values (96, 'jobs - medical / health', 'hea');
insert into category (category_id, name, external_name) values (97, 'jobs - nonprofit sector', 'npo');
insert into category (category_id, name, external_name) values (98, 'jobs - real estate', 'rej');
insert into category (category_id, name, external_name) values (99, 'jobs - retail / wholesale', 'ret');
insert into category (category_id, name, external_name) values (100, 'jobs - sales / biz dev', 'sls');
insert into category (category_id, name, external_name) values (101, 'jobs - salon / spa / fitness', 'spa');
insert into category (category_id, name, external_name) values (102, 'jobs - security', 'sec');
insert into category (category_id, name, external_name) values (103, 'jobs - skilled trade / craft', 'trd');
insert into category (category_id, name, external_name) values (104, 'jobs - software / qa / dba', 'sof');
insert into category (category_id, name, external_name) values (105, 'jobs - systems / network', 'sad');
insert into category (category_id, name, external_name) values (106, 'jobs - technical support', 'tch');
insert into category (category_id, name, external_name) values (107, 'jobs - transport', 'trp');
insert into category (category_id, name, external_name) values (108, 'jobs - tv / film / video', 'tfr');
insert into category (category_id, name, external_name) values (109, 'jobs - web / info design', 'web');
insert into category (category_id, name, external_name) values (110, 'jobs - writing / editing', 'wri');
insert into category (category_id, name, external_name) values (111, 'jobs - etc', 'etc');
insert into category (category_id, name, external_name) values (112, 'jobs - part time', 'jjj?addFour=part-time');
insert into category (category_id, name, external_name) values (113, 'gigs - crew', 'cwg');
insert into category (category_id, name, external_name) values (114, 'gigs - event', 'evg');
insert into category (category_id, name, external_name) values (115, 'gigs - labor', 'lbg');
insert into category (category_id, name, external_name) values (116, 'gigs - computer', 'cpg');
insert into category (category_id, name, external_name) values (117, 'gigs - creative', 'crg');
insert into category (category_id, name, external_name) values (118, 'gigs - domestic', 'dmg');
insert into category (category_id, name, external_name) values (119, 'gigs - talent', 'tlg');
insert into category (category_id, name, external_name) values (120, 'gigs - writing', 'wrg');
insert into category (category_id, name, external_name) values (121, 'gigs - adult', 'adg');
insert into category (category_id, name, external_name) values (122, 'resumes', 'res');
